"""strengthen data validation

Revision ID: b7dc0b75e779
Revises: 2962fae893fa
Create Date: 2026-02-12 10:47:40.456760

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa # noqa: F401
import sqlmodel # noqa: F401


# revision identifiers, used by Alembic.
revision: str = 'b7dc0b75e779'
down_revision: Union[str, Sequence[str], None] = '2962fae893fa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_product_name'), 'product', type_='unique')
    op.create_index(op.f('ix_product_name'), 'product', ['name'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_product_name'), table_name='product')
    op.create_unique_constraint(op.f('uq_product_name'), 'product', ['name'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
