"""agregar campos code y validaciones extra para campo name

Revision ID: b9ce3962257b
Revises: fc3dbc4d8159
Create Date: 2026-01-15 09:27:59.406017

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'b9ce3962257b'
down_revision: Union[str, Sequence[str], None] = 'fc3dbc4d8159'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('brand', sa.Column('code', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.create_index(op.f('ix_brand_code'), 'brand', ['code'], unique=True)
    op.add_column('category', sa.Column('code', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.create_index(op.f('ix_category_code'), 'category', ['code'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_category_code'), table_name='category')
    op.drop_column('category', 'code')
    op.drop_index(op.f('ix_brand_code'), table_name='brand')
    op.drop_column('brand', 'code')
    # ### end Alembic commands ###
