"""add missing field to ProductImage

Revision ID: baf21bac54ba
Revises: 161a9fecd33a
Create Date: 2026-02-24 09:09:37.623682

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel # noqa: F401


# revision identifiers, used by Alembic.
revision: str = 'baf21bac54ba'
down_revision: Union[str, Sequence[str], None] = '161a9fecd33a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product_image', sa.Column('is_main', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('product_image', 'is_main')
    # ### end Alembic commands ###
