"""add is_active field to auditmixin

Revision ID: dc9f3ea0f047
Revises: fd86e5682ba5
Create Date: 2026-02-06 10:34:36.779501

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'dc9f3ea0f047'
down_revision: Union[str, Sequence[str], None] = 'fd86e5682ba5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('brand', sa.Column('is_active', sa.Boolean(), nullable=False))
    op.add_column('category', sa.Column('is_active', sa.Boolean(), nullable=False))
    op.add_column('user', sa.Column('is_active', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'is_active')
    op.drop_column('category', 'is_active')
    op.drop_column('brand', 'is_active')
    # ### end Alembic commands ###
