"""crear tabla brand

Revision ID: fc3dbc4d8159
Revises: e729e92d0a0a
Create Date: 2026-01-09 09:38:11.964821

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'fc3dbc4d8159'
down_revision: Union[str, Sequence[str], None] = 'e729e92d0a0a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('brand',
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('brand_id', sa.Uuid(), nullable=False),
    sa.PrimaryKeyConstraint('brand_id')
    )
    op.create_index(op.f('ix_brand_name'), 'brand', ['name'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_brand_name'), table_name='brand')
    op.drop_table('brand')
    # ### end Alembic commands ###
